accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: wallet
    address: cosmos1z3978xhvm0yrctl2hf9jhrnktzzz5x690sh0qa
    coins: ["10000token", "100000000stake"]
  - name: mobile_wallet
    address: cosmos1c6f7sj6pvpl2ettcn6uxvc002495qc65f49xwl
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
